apiVersion: v1
kind: ConfigMap
metadata:
  name: router-cm-{{.Release.Name }}
data:
  router.toml: |
    [secrets_management]
    secrets_manager = "{{ .Values.application.server.secrets_manager }}" # Secrets manager client to be used
    [encryption_management]
    encryption_manager = "{{ .Values.application.server.encryption_manager }}" # Encryption manager client to be used
    [locker]
    host = "{{ .Values.application.server.locker.host }}"
    host_rs = "{{ .Values.application.server.locker.host_rs}}"
    mock_locker = {{ .Values.application.server.locker.mock_locker }}
    locker_signing_key_id = "{{ .Values.application.server.locker.locker_signing_key_id }}"
    locker_enabled = {{ .Values.application.server.locker.locker_enabled }}
    [payment_link]
    sdk_url = "{{ .Values.application.server.payment_link.sdk_url }}"
    [opensearch]
    host = "{{ .Values.application.server.opensearch.host }}"
    
    {{- if eq .Values.application.server.run_env "production" -}}
    {{ .Files.Get "configs/misc.toml" | nindent 4 }}
    {{ .Files.Get "configs/router-production.toml" | nindent 4 }}
    {{- else -}}
    {{ .Files.Get "configs/misc.toml" | nindent 4 }}
    {{ .Files.Get "configs/router-sandbox.toml" | nindent 4 }}
    {{- end }}