apiVersion: v1
data:
  BACH__KEYS__TEMP_CARD_KEY: ""
  BACH_READ_USER_PWD: ""
  ROUTER__ANALYTICS__SQLX__DBNAME: ""
  ROUTER__ANALYTICS__SQLX__KMS_ENCRYPTED_PASSWORD: ""
  ROUTER__ANALYTICS__SQLX__USERNAME: ""
  ROUTER__API_KEYS__KMS_ENCRYPTED_HASH_KEY: {{ .Values.application.server.secrets.kms_encrypted_api_hash_key | toString | b64enc }}
  ROUTER__JWEKEY__LOCKER_DECRYPTION_KEY1: {{ .Values.application.server.secrets.kms_jwekey_locker_decryption_key1 | b64enc }}
  ROUTER__JWEKEY__LOCKER_DECRYPTION_KEY2: {{ .Values.application.server.secrets.kms_jwekey_locker_decryption_key2 | b64enc }}
  ROUTER__JWEKEY__LOCKER_ENCRYPTION_KEY1: {{ .Values.application.server.secrets.kms_jwekey_locker_encryption_key1 | b64enc }}
  ROUTER__JWEKEY__LOCKER_ENCRYPTION_KEY2: {{ .Values.application.server.secrets.kms_jwekey_locker_encryption_key2 | b64enc }}
  ROUTER__JWEKEY__LOCKER_KEY_IDENTIFIER1: {{ .Values.application.server.secrets.kms_jwekey_locker_identifier1 | b64enc }}
  ROUTER__JWEKEY__LOCKER_KEY_IDENTIFIER2: {{ .Values.application.server.secrets.kms_jwekey_locker_identifier2 | b64enc }}
  ROUTER__JWEKEY__TUNNEL_PRIVATE_KEY: {{ .Values.application.server.secrets.kms_jwekey_tunnel_private_key | b64enc }}
  ROUTER__JWEKEY__VAULT_ENCRYPTION_KEY: {{ .Values.application.server.secrets.kms_jwekey_vault_encryption_key | b64enc }}
  ROUTER__JWEKEY__VAULT_PRIVATE_KEY: {{ .Values.application.server.secrets.kms_jwekey_vault_private_key | b64enc }}
  ROUTER__KMS__KEY_ID: {{ .Values.application.server.secrets.kms_key_id | b64enc }}
  ROUTER__KMS__REGION: {{ .Values.application.server.secrets.kms_key_region | b64enc }}
  ROUTER__JWEKEY__RUST_LOCKER_ENCRYPTION_KEY: {{ .Values.application.server.secrets.kms_jwekey_rust_locker_encryption_key | b64enc }}
  ROUTER__LOCKER__BASILISK_HOST: ""
  ROUTER__SECRETS__KMS_ENCRYPTED_ADMIN_API_KEY: {{ .Values.application.server.secrets.kms_admin_api_key | b64enc }}
  ROUTER__SECRETS__KMS_ENCRYPTED_JWT_SECRET: {{ .Values.application.server.secrets.kms_jwt_secret | b64enc}}
  ROUTER__SECRETS__MASTER_ENC_KEY: {{ .Values.application.server.master_enc_key | b64enc }}
  ROUTER__SECRETS__KMS_ENCRYPTED_RECON_ADMIN_API_KEY: {{ .Values.application.server.secrets.recon_admin_api_key | toString | b64enc}}
  ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_ID: {{ .Values.application.server.secrets.kms_connector_onboarding_paypal_client_id | b64enc}}
  ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_SECRET: {{ .Values.application.server.secrets.kms_connector_onboarding_paypal_client_secret | b64enc}}
  ROUTER__CONNECTOR_ONBOARDING__PAYPAL__PARTNER_ID: {{ .Values.application.server.secrets.kms_connector_onboarding_paypal_partner_id | b64enc}}
kind: Secret
metadata:
  name: hyperswitch-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
