{{- if .Values.initDB.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-locker-db
  labels:
    app: create-locker-db
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        {{- include "postgresql.initContainer.check.ready" . | nindent 8 }}
      containers:
        - name: run-locker-db-migration
          image: {{ .Values.initDB.migration.image }}
          command: [ '/bin/sh', '-c' ]
          #language=sh
          args:
            - |-
              apt update
              apt install -y git
              git clone https://github.com/juspay/hyperswitch-card-vault.git
              cd hyperswitch-card-vault
              diesel migration --database-url postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$DBNAME run
              echo "Completed hyperswitch database migration"
          env:
            - name: POSTGRES_HOST
              value: {{ include "postgresql.host" . }}
            - name: DBNAME
              value: {{ include "postgresql.name" . }}
            - name: POSTGRES_USER
              value: {{ include "postgresql.username" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__DATABASE__PASSWORD
{{- end }}

