apiVersion: v1
kind: Service
metadata:
  name: hyperswitch-server
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: hyperswitch-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  {{- with (default .Values.application.global.annotations .Values.application.server.serviceAccountAnnotations) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: hyperswitch-router-role
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
  {{- with (default .Values.application.global.annotations .Values.application.server.annotations) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: hyperswitch-server-v1o52o1v2
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: {{ default .Values.application.global.progressDeadlineSeconds .Values.application.server.progressDeadlineSeconds  }}
  replicas: {{ default .Values.application.global.replicas .Values.application.server.replicas  }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.application.server.labels.app }}
      version: v1o52o1v2
  strategy:
  {{- with (default .Values.application.global.strategy .Values.application.server.strategy) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-09-20T12:11:41+05:30"
        traffic.sidecar.istio.io/excludeOutboundIPRanges: {{ default .Values.application.global.podAnnotations.traffic_sidecar_istio_io_excludeOutboundIPRanges .Values.application.server.podAnnotations.traffic_sidecar_istio_io_excludeOutboundIPRanges  }}
      creationTimestamp: null
      labels:
        app: {{ .Values.application.server.labels.app }}
        version: v1o52o1v2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- with (default .Values.application.global.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution .Values.application.server.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      initContainers:
        {{- include "postgresql.initContainer.check.ready" . | nindent 8 }}
      containers:
      - env:
        - name: BINARY
          value: {{ .Values.application.server.env.binary }}
        - name: {{ .Values.application.global.env.pod_name.name }}
          valueFrom:
            {{- with .Values.application.global.env.pod_name.valueFrom.fieldRef }}
            fieldRef:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        - name: ROUTER__ANALYTICS__CLICKHOUSE__PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.secret" . }}
              key: password
        - name: ROUTER__ANALYTICS__SQLX__PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.secret" . }}
              key: password
        - name: ROUTER__MASTER_DATABASE__PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.secret" . }}
              key: password
        - name: ROUTER__REPLICA_DATABASE__PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.secret" . }}
              key: password
        - name: ROUTER__JWEKEY__VAULT_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__VAULT_ENCRYPTION_KEY
              name: hyperswitch-secrets
        - name: ROUTER__JWEKEY__VAULT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__VAULT_PRIVATE_KEY
              name: hyperswitch-secrets
        - name: ROUTER__SECRETS__KMS_ENCRYPTED_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: ROUTER__SECRETS__KMS_ENCRYPTED_JWT_SECRET
              name: hyperswitch-secrets
        - name: ROUTER__SECRETS__KMS_ENCRYPTED_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              key: ROUTER__SECRETS__KMS_ENCRYPTED_ADMIN_API_KEY
              name: hyperswitch-secrets
        - name: ROUTER__KMS__KEY_ID
          valueFrom:
            secretKeyRef:
              key: ROUTER__KMS__KEY_ID
              name: hyperswitch-secrets
        - name: ROUTER__KMS__REGION
          valueFrom:
            secretKeyRef:
              key: ROUTER__KMS__REGION
              name: hyperswitch-secrets
        - name: ROUTER__API_KEYS__KMS_ENCRYPTED_HASH_KEY
          valueFrom:
            secretKeyRef:
              key: ROUTER__API_KEYS__KMS_ENCRYPTED_HASH_KEY
              name: hyperswitch-secrets
        - name: ROUTER__JWEKEY__LOCKER_KEY_IDENTIFIER1
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__LOCKER_KEY_IDENTIFIER1
              name: hyperswitch-secrets
        - name: ROUTER__JWEKEY__LOCKER_KEY_IDENTIFIER2
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__LOCKER_KEY_IDENTIFIER2
              name: hyperswitch-secrets
        - name: ROUTER__JWEKEY__LOCKER_ENCRYPTION_KEY1
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__LOCKER_ENCRYPTION_KEY1
              name: hyperswitch-secrets
        - name: ROUTER__JWEKEY__LOCKER_ENCRYPTION_KEY2
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__LOCKER_ENCRYPTION_KEY2
              name: hyperswitch-secrets
        - name: ROUTER__JWEKEY__LOCKER_DECRYPTION_KEY1
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__LOCKER_DECRYPTION_KEY1
              name: hyperswitch-secrets
        - name: ROUTER__JWEKEY__LOCKER_DECRYPTION_KEY2
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__LOCKER_DECRYPTION_KEY2
              name: hyperswitch-secrets
        - name: ROUTER__SECRETS__MASTER_ENC_KEY
          valueFrom:
            secretKeyRef:
              key: ROUTER__SECRETS__MASTER_ENC_KEY
              name: hyperswitch-secrets
        - name: ROUTER__ANALYTICS__SQLX__KMS_ENCRYPTED_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ include "postgresql.secret" . }}
        - name: ROUTER__JWEKEY__TUNNEL_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__TUNNEL_PRIVATE_KEY
              name: hyperswitch-secrets
        - name: ROUTER__JWEKEY__RUST_LOCKER_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: ROUTER__JWEKEY__RUST_LOCKER_ENCRYPTION_KEY
              name: hyperswitch-secrets

        - name: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_ID
              name: hyperswitch-secrets

        - name: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_SECRET
              name: hyperswitch-secrets

        - name: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__PARTNER_ID
          valueFrom:
            secretKeyRef:
              key: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__PARTNER_ID
              name: hyperswitch-secrets

        envFrom:
          - configMapRef:
              name: router-cm-{{.Release.Name }}
        image: {{ .Values.services.router.image }}
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - pkill -15 node
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: bach
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /local/config/production.toml
          name: hyperswitch-config
          subPath: production.toml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: hyperswitch-router-role
      serviceAccountName: hyperswitch-router-role
      terminationGracePeriodSeconds: {{ default .Values.application.global.terminationGracePeriodSeconds .Values.application.server.terminationGracePeriodSeconds  }}
      volumes:
      - configMap:
          defaultMode: 420
          name: hyperswitch-config
        name: hyperswitch-config
