{{- if .Values.redis.internal }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    app: redis
spec:
  serviceName: redis  
  replicas: 1       # Number of Redis instances you want to run. please change ROUTER__REDIS__CLUSTER_ENABLED to true in server-deployment when increasing the number of replicas
  selector:
    matchLabels:
      role: master
      app: redis
  template:
    metadata:
      labels:
        role: master
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest   # Use the official Redis Docker image.
        ports:
        - containerPort: 6379  # Redis default port
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "4Gi"
            cpu: "200m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data:
  master.conf: |
    bind 0.0.0.0
    protected-mode yes
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
  slave.conf: |
    slaveof redis-0.redis 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  clusterIP: None
  selector:
    app: redis
    role: master
{{- end }}