apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
  {{- with (default .Values.application.global.annotations .Values.application.controlCenter.annotations) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  generation: 1
  name: hyperswitch-control-center-0f746cb72517
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: {{ default .Values.application.global.progressDeadlineSeconds .Values.application.controlCenter.progressDeadlineSeconds}}
  replicas: {{ default .Values.application.global.replicas .Values.application.controlCenter.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.application.controlCenter.labels.app }}
      version: 0f746cb72517
  strategy:
  {{- with (default .Values.application.global.strategy .Values.application.controlCenter.strategy) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.application.controlCenter.labels.app }}
        version: 0f746cb72517
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- with (default .Values.application.global.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution .Values.application.controlCenter.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      containers:
      - env:
        - name: apiBaseUrl
          value: {{ .Values.services.router.host }}
        - name: sdkBaseUrl
          value: "{{ .Values.services.sdkDemo.host }}/{{ .Values.services.sdkDemo.version }}/{{ .Values.services.sdkDemo.subversion }}/HyperLoader.js"
        image: {{ .Values.services.controlCenter.image }}
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - pkill -15 node
        name: hyperswitch-control-center
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /local/config/production.toml
          name: hyperswitch-config
          subPath: production.toml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: hyperswitch-router-role
      serviceAccountName: hyperswitch-router-role
      terminationGracePeriodSeconds: {{ .Values.application.controlCenter.terminationGracePeriodSeconds}}
      volumes:
      - configMap:
          defaultMode: 420
          name: hyperswitch-config
        name: hyperswitch-config
---
apiVersion: v1
kind: Service
metadata:
  name: hyperswitch-control-center
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9000
  selector:
    app: hyperswitch-control-center
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyperswitch-control-center-role
  namespace: {{ .Release.Namespace }}