# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: redis
#   labels:
#     app: redis
# spec:
#   serviceName: redis  # This is the name used for the headless service.
#   replicas: 3       # Number of Redis instances you want to run.
#   selector:
#     matchLabels:
#       role: master
#       app: redis     # Label to select the pods
#   template:
#     metadata:
#       labels:
#         role: master
#         app: redis   # Label applied to the pods
#     spec:
#       containers:
#       - name: redis
#         image: redis:latest   # Use the official Redis Docker image.
#         ports:
#         - containerPort: 6379  # Redis default port
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "100m"
#           limits:
#             memory: "256Mi"
#             cpu: "200m"
