apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
  {{- with (default .Values.application.global.annotations .Values.application.sdk.annotations) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  generation: 1
  name: {{ .Values.application.sdk.labels.app }}-0f746cb72517
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: {{ default .Values.application.global.progressDeadlineSeconds .Values.application.sdk.progressDeadlineSeconds}}
  replicas: {{ default .Values.application.global.replicas .Values.application.sdk.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.application.sdk.labels.app }}
      version: 0f746cb72517
  strategy:
  {{- with (default .Values.application.global.strategy .Values.application.sdk.strategy) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.application.sdk.labels.app }}
        version: 0f746cb72517
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- with (default .Values.application.global.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution .Values.application.sdk.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      containers:
      - env:
        - name: HYPERSWITCH_PUBLISHABLE_KEY
          value: {{ .Values.services.sdkDemo.hyperswitchPublishableKey }}
        - name: HYPERSWITCH_SECRET_KEY
          value: {{ .Values.services.sdkDemo.hyperswitchSecretKey }}
        - name: HYPERSWITCH_SERVER_URL
          value: {{ .Values.services.router.host }}
        - name: HYPERSWITCH_CLIENT_URL
          value: "{{ .Values.services.sdkDemo.host }}/{{.Values.services.sdkDemo.version}}/{{.Values.services.sdkDemo.subversion}}"
        image: {{ .Values.services.sdkDemo.image }}
        ports:
        - containerPort: 5252
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - pkill -15 node
        name: {{ .Values.application.sdk.labels.app }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: hyperswitch-router-role
      serviceAccountName: hyperswitch-router-role
      terminationGracePeriodSeconds: {{ .Values.application.sdk.terminationGracePeriodSeconds}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.sdk.labels.app }}
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5252
  - name: https
    port: 443
    protocol: TCP
    targetPort: 5252
  selector:
    app: {{ .Values.application.sdk.labels.app }}
  sessionAffinity: None
  type: ClusterIP