apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes to deploy hyperswitch application
name: hyperswitch-helm
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: 18.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.27
    condition: postgresql.enabled
  - name: hyperswitchsdk
    version: 0.1.0
    repository: "file://../hyperswitch-sdk"
    condition: hyperswitchsdk.enabled