apiVersion: v1
kind: Service
metadata:
  name: hyperswitch-sdk
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5252
  - name: https
    port: 443
    protocol: TCP
    targetPort: 5252
  selector:
    app: hyperswitch-sdk
  sessionAffinity: None
  type: ClusterIP

