apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
  {{- with (default .Values.application.global.annotations .Values.application.sdk.annotations) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  generation: 1
  name: {{ .Values.application.sdk.labels.app }}-0f746cb72517
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: {{ default .Values.application.global.progressDeadlineSeconds .Values.application.sdk.progressDeadlineSeconds}}
  replicas: {{ default .Values.application.global.replicas .Values.application.sdk.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.application.sdk.labels.app }}
      version: 0f746cb72517
  strategy:
  {{- with (default .Values.application.global.strategy .Values.application.sdk.strategy) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.application.sdk.labels.app }}
        version: 0f746cb72517
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- with (default .Values.application.global.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution .Values.application.sdk.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      containers:
      - env:
        - name: HYPERSWITCH_PUBLISHABLE_KEY
          value: {{ .Values.application.sdk.env.hyperswitchPublishableKey }}
        - name: HYPERSWITCH_SECRET_KEY
          value: {{ .Values.application.sdk.env.hyperswitchSecretKey }}
        - name: HYPERSWITCH_SERVER_URL
          value: {{ .Values.application.sdk.env.hyperswitchServerUrl }}
        - name: HYPERSWITCH_CLIENT_URL
          value: {{ .Values.application.sdk.env.hyperSwitchClientUrl }}
        - name: SELF_SERVER_URL
          value: {{ .Values.application.sdk.env.selfServerUrl }}
        image: {{ .Values.application.sdk.image }}
        ports:
        - containerPort: 5252
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - pkill -15 node
        name: {{ .Values.application.sdk.labels.app }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /local/config/production.toml
          name: hyperswitch-config
          subPath: production.toml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: hyperswitch-router-role
      serviceAccountName: hyperswitch-router-role
      terminationGracePeriodSeconds: {{ .Values.application.sdk.terminationGracePeriodSeconds}}
      volumes:
      - configMap:
          defaultMode: 420
          name: hyperswitch-config
        name: hyperswitch-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.sdk.labels.app }}
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5252
  - name: https
    port: 443
    protocol: TCP
    targetPort: 5252
  selector:
    app: {{ .Values.application.sdk.labels.app }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.application.sdk.labels.app }}-ingress"
  namespace: hyperswitch
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP1
    alb.ingress.kubernetes.io/group.name: "{{ .Values.application.sdk.labels.app }}-alb-ingress-group"
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.application.sdk.labels.app }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: {{ .Values.loadBalancer.targetSecurityGroup }}
    alb.ingress.kubernetes.io/tags: stack=hyperswitch-lb
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.application.sdk.labels.app }}
                port:
                  number: 80