apiVersion: v1
kind: Secret
metadata:
  name: producer-secret-{{.Release.Name }}
data:
  ROUTER__FILE_UPLOAD_CONFIG__BUCKET_NAME: {{ "bucket" | b64enc }}
  ROUTER__FILE_UPLOAD_CONFIG__REGION: {{ "us-east-1"  | b64enc }}
  ROUTER__MASTER_DATABASE__HOST: {{ include "postgresql.host" . | b64enc }}
  ROUTER__MASTER_DATABASE__DBNAME: {{ .Values.postgresql.global.postgresql.auth.database | b64enc }}
  ROUTER__MASTER_DATABASE__PORT: {{ include "postgresql.port" . | toString | b64enc }}
  ROUTER__MASTER_DATABASE__USERNAME: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  ROUTER__REDIS__HOST: {{ include "redis.host" . | b64enc }}
  ROUTER__REDIS__PORT: {{ include "redis.port" . | toString | b64enc }}
  {{- /*  TODO manage replicas  */}}
  ROUTER__REPLICA_DATABASE__HOST: {{ include "postgresql.host" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__USERNAME: {{ include "postgresqlreplica.username" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__HOST: {{ include "postgresqlreplica.host" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__PORT: {{ include "postgresqlreplica.port" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__DBNAME: {{ .Values.postgresql.global.postgresql.auth.database | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__USERNAME: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__DATABASE_NAME: {{ .Values.postgresql.global.postgresql.auth.database | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__HOST: {{ include "postgresql.host" . | b64enc }}

