apiVersion: v1
entries:
  hyperswitch-istio:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-05-29T16:23:32.270296+05:30"
    description: A Helm chart for Kubernetes
    digest: 424006ebd4fa077432e142ff355aac5d23b177e85b97a50fff6c3ed4a94fee19
    name: hyperswitch-istio
    type: application
    urls:
    - https://juspay.github.io/hyperswitch-helm/charts/incubator/hyperswitch-istio-0.1.0.tgz/hyperswitch-istio-0.1.0.tgz
    version: 0.1.0
generated: "2024-05-29T16:23:32.269456+05:30"
