apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-s3-cm
  namespace: logging
data:
    fluent.conf: |
      {{ .Files.Get "configs/fluent.conf" | nindent 6 }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: fluentd-s3
  name: fluentd-s3
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluentd-s3
  template:
    metadata:
      labels:
        app: fluentd-s3
    spec:
      containers:
      - env:
        - name: S3_BUCKET
          value:  {{ .Values.application.server.bucket_name }}
        - name: S3_REGION
          value: "us-east-1"
        image: docker.io/fluent/fluentd-kubernetes-daemonset:v1.16-debian-s3-1
        imagePullPolicy: IfNotPresent
        name: fluentd-s3
        resources:
          limits:
            cpu: "1"
            memory: 1200Mi
          requests:
            cpu: 200m
            memory: 150Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluentd/etc
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: app-logs-s3-service-account
      serviceAccountName: app-logs-s3-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: fluentd-s3-cm
        name: config
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers