apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-cm-{{ .Release.Name }}
data: 
  consumer.toml: |
    [secrets_management]
    secrets_manager = "{{ .Values.application.server.secrets_manager }}" # Secrets manager client to be used

    [encryption_management]
    encryption_manager = "{{ .Values.application.server.encryption_manager }}" # Encryption manager client to be used

    {{- if eq .Values.application.server.run_env "production" -}}
    {{ .Files.Get "configs/consumer.toml" | nindent 4 }}
    {{ .Files.Get "configs/misc.toml" | nindent 4 }}
    {{ .Files.Get "configs/router-production.toml" | nindent 4 }}
    {{- else -}}
    {{ .Files.Get "configs/consumer.toml" | nindent 4 }}
    {{ .Files.Get "configs/misc.toml" | nindent 4 }}
    {{ .Files.Get "configs/router-sandbox.toml" | nindent 4 }}
    {{- end }}

