apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with (default .Values.application.global.annotations .Values.application.consumer.annotations) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: hyperswitch-consumer-v1o111o0
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: {{ default .Values.application.global.progressDeadlineSeconds .Values.application.consumer.progressDeadlineSeconds }}
  replicas: {{ default .Values.application.global.replicas .Values.application.consumer.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.application.consumer.labels.app }}
      version: consumer-v1o111o0
  strategy:
    {{- with (default .Values.application.global.strategy .Values.application.consumer.strategy) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-04-21T14:21:23+05:30"
        checksum/consumer-config: {{ include (print $.Template.BasePath "/consumer/configmap.yaml") . | sha256sum }}
        checksum/consumer-secret: {{ include (print $.Template.BasePath "/consumer/secret.yaml") . | sha256sum }}
        checksum/misc-secrets: {{ include (print $.Template.BasePath "/misc/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.application.consumer.labels.app }}
        version: consumer-v1o111o0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- with (default .Values.application.global.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution .Values.application.consumer.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution) }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      initContainers:
        {{- include "postgresql.initContainer.check.ready" . | nindent 8 }}
        {{- if .Values.redisMiscConfig.checkRedisIsUp.initContainer.enable }}
        {{- include "redis.initContainer.check.ready" . | nindent 8 }}
        {{- end }}
      containers:
        - name: hyperswitch-consumer
          image: {{ .Values.services.consumer.image }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - pkill -15 node
          env:
          {{- include "generic.envs" . | nindent 12 }}
          {{- include "postgresql.secrets.envs" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: consumer-secret-{{ .Release.Name }}
            - secretRef:
                name: hyperswitch-secrets
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts: 
            {{- if eq .Values.application.server.run_env "production" }}
            - mountPath: /local/config/production.toml
              name: hyperswitch-config
              subPath: consumer.toml
            {{- else }}
            - mountPath: /local/config/sandbox.toml
              name: hyperswitch-config
              subPath: consumer.toml
            {{- end }}

            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: hyperswitch-router-role
      terminationGracePeriodSeconds: {{ .Values.application.consumer.terminationGracePeriodSeconds }}
      volumes:
        - configMap:
            defaultMode: 420
            name: consumer-cm-{{ .Release.Name }}
          name: hyperswitch-config
