server:
  secrets:
    master_key: a164665dd3a545c194aa297e4d2cdbd19aa3c59865907e9ffffb7b8d9fcb476208f84fe53bbc7801f2b8eb1aab633fb24ad0bb99b275066fb56516ef
    locker_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA4EXw24jOqrjZzhZG7ef9MYNWqHfTHKfliRRxZOWkjYIUuGjH
      xxIE5mjo6VK8KQljbpK1EXYsWYjaTBiLzYzagTu7uacw2dTvPIIbxJcxDfmDFoct
      XppRrwjHizEayLoixwe93zQ6W+QXLVMI6muJUgpiJ8+vvfYUbN9AWDgiAmVQV08P
      8CRvFGXI4Yyn7Tcg+7tLbAYr+z8ZvmUBPcAKboqJzZBgPpTZe0k4sIwPVIDnPVVH
      9Jk/tmU/MhjEL1XIMYBX7/S+uOQrr5NRhSvHHBi6iF/OzzYnOz4Jhcb2m9zyT1qv
      ObY59avDovK4fI3KdQsd7tvfu9h2438JiHrjSwIDAQABAoIBAQCUDLeuRMahHrvx
      dvVF0fJrwBbxyYAcl51H+63LfGk/XRLOlaTj/jor3C987zf1IxR3hvNu3oLybAwn
      VcDcZVJNI6COMxdlhVKUsBMimOgyIHdv5LaHj/nCQVpwwW67+VxB5RNriC/KP20p
      Z3ooPer9tIsNWuXZ0duz70CrvAp/ZyPboS5iICRMTzkimWeEy6wPunpk5YOQhyPn
      GL5Gd2DNRqCGnk1GWUwBCY9/iWs0TW5jx8K6PUlwswQHU+Me8zeXo1iT4nMr2yId
      BTlwOia9ZHjDqEulrV/2YERsLKbdLTy7jhxK/uibZuxol5/hr8ELQkoHzu6yFOU/
      kYYIPAtBAoGBAPKtuZvR7nO1AWx+qaAtHicMQcazGatxQfz1rfJ/ny8ayEN/GVye
      rvcNbJMwAG38VIUh0so8VgITgEX/mbGndxL5jpstTd1SXM1walBTu59kFVsnmQZn
      hUyO8oxMZNDpgS1Dc2eX/JGBEYmJbz/5DyDa1pAglp8Ej8KJnBc9d82rAoGBAOyV
      kj8PzJSduMS7oZoek/HKdvelWBNpeBC9rnCXAVbyjYv5rU5VISr0mfAJK54jjxXn
      PEYApJgSB8fTxFHh3TapBjExkkm293o5CKVrSbv9v0yPbZh1FOBa6DK3hBs8Zwlq
      iikD2Dqof/qcJML5njWO5TaN/DfySaxIeSdKLWDhAoGBALCA7kiIrbf2ZGy2y0S2
      zAF2hriwNvFc1LPZNIT1kZ+/CP0eiiG1QGhrmRaMiSN1rTuPWDLDI4MrD9bZir2N
      oatpWvE+SC2648iABLMb05CgSHAeIsxnqqn+JicowQK5cryrHFqyTn69szWnggSz
      bu9kez4klahetvi1AZRdnq81AoGADbXlUc5CluJFEPGmvd3DySFon5Vvc0CLerzj
      XRcDNty7oz8G8iEw2OJwAV8mrfV1l1ldPtlOsJlq5gO5vt0OCtrkxvkOd0MpOGYR
      wDRlg4WDDpbJTSqL2SyrhDTqbQGlHwCTnSjh4RRexlFCOCJrLsNnOTAlS8C40Ekq
      7EH6O0ECgYEAksw52Si+wcCzsfjT1WCywlJ4SFaQIpYt5/zuOiY+XUtcZfVEuRWa
      FkN/n61HQVy+Quv918VHldElTDqv6O0x/OU2xvjiXCoQh4zTcAXxw4cCTGxxNM4J
      LubCEvK1De5p5JZYVarob+X2uOIdVRpcD9PYIslKDz0OwfhiFwEkqdQ=
      -----END RSA PRIVATE KEY-----
    tenant_public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsM2GTqIlJxx1bA9HFFPJ
      2HFIJGh9iWJTqn9OWoayOUpM01fT86ZMR6ozCPKiKGk1nkKcSS+wWemrMBGZD76H
      rcnx93rHZzkx/F1/Rxtuy3Dp1GMmVZ+jO8ZMIRl5LBBtAXG4BTC/+ckrGcEocrT1
      YvqshrWinXbBfkCyzE+tBo++6oFwsdMBZdLfF4C3nnSJxQaUgddQ9dItG6ywDM55
      jvKpQL6TnhPxc2Th0T1UEVGWbw8VOyhLfYXa8+nB7z3zebvIIrZgu5DIu4k8A8yu
      kyW98E7XBg8vOG9qIEXfhkWHQZfApZdQVIpwczXateiKKbtSVFMQHeafo6dIq90B
      1wIDAQAB
      -----END PUBLIC KEY-----
