apiVersion: v1
entries:
  hyperswitch-card-vault:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-05T15:34:37.66241+05:30"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 13.2.27
    description: A Helm chart for creating Hyperswitch Card Vault
    digest: 79a76ca3be81ca4fc182881daaaff515e05817e8dacc63474bd15b70eaf644f7
    name: hyperswitch-card-vault
    type: application
    urls:
    - https://juspay.github.io/hyperswitch-helm/charts/incubator/hyperswitch-card-vault/hyperswitch-card-vault-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r93
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.15.0-debian-11-r4
        - name: postgresql
          image: docker.io/bitnami/postgresql:16.1.0-debian-11-r18
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 16.1.0
    created: "2024-02-05T15:34:37.665347+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 9e3ab42d8197aac72722a3557d1f8ed04adc0fd5768e1985569bc73eaddc3b9c
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://juspay.github.io/hyperswitch-helm/charts/incubator/hyperswitch-card-vault/charts/postgresql-13.2.27.tgz
    version: 13.2.27
generated: "2024-02-05T15:34:37.657992+05:30"
