# Default values for helm.
global:
  # Annotations to be added to all resources
  annotations: {}

  # Node affinity to be added to all resources
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      # matchExpression:
      - key: node-type
        operator: In
        values:
          - generic-compute

# Values for hyperswitch-card-vault.
server:
  # Annotations to be added to hyperswitch-card-vault.
  annotations: {}

  # Image to be used for hyperswitch-card-vault.
  image: juspaydotin/hyperswitch-card-vault:v1.3.0-nokms

  # values to be used in pod template.
  pod:
    # Annotations to be added to hyperswitch-card-vault pod.
    annotations: {}

  # Node affinity to be added to hyperswitch-card-vault.
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      # matchExpression:
      - key: node-type
        operator: In
        values:
          - generic-compute
      # - key: spot-instance
      #   operator: NotIn
      #   values:
      #     - "true"
      # - key: <label for the node>
      #   operator: In
      #   values:
      #     - <Value for the label>

  # Secrets to be added to hyperswitch-card-vault.
  secrets:
    master_key: # <value for the secret>
    locker_private_key: # <value for the secret>
    tenant_public_key: # <value for the secret>

  # Extra values to be added to hyperswitch-card-vault.
  extra:
    # extra env variables to be added to hyperswitch-card-vault.
    env: {}

# Values for database (postgresql).
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: # <value for the secret>
        password: # <value for the secret>
        database: # <value for the secret>
        architecture: standalone

external:
  postgresql:
    enabled: false
    config:
      host: # <value for the secret>
      port: # <value for the secret>
      username: # <value for the secret>
      password: # <value for the secret>
      database: # <value for the secret>

# Values for the database migration job
initDB:
  # Should we run the migrations on the database
  enable: false
  checkPGisUp:
    image: postgres:16-alpine3.19
    maxAttempt: 30
  migration:
    image: christophwurst/diesel-cli:latest
